### ISSUE TITLE
Jurassic Park Arcade Black Text

### ISSUE THREAD

**Issue by nehrujuman** [teknogods/teknoparrot-issues#226]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.140
**Did this issue happen with an older version**: Don't known, didn't try
**Game with issue**: Jurassic Park Arcade
**Detailed description of issue**: The text is pure black, unreadable; but the 3d graphics seem to be working ok
**Reproduction details**: just started the game normally
**Any other details**:
**Pictures of issue**:

**Comment by Yoda-XY** [comment]
Same Problem here. Have u managed it?

**Comment by Yoda-XY** [comment]
Hey i have fixed it. i deactivated the onboard graphics card in the system settings then i set the 3d settings in nvidia settings manager to high performance in global settings and also set teknoparrot to global setting in the program settings tab and now i have text yeahh

**Comment by romadu** [comment]
I have the same issue. Tried applying the graphics settings in nvidia control panel, but issue persists.

**Comment by oferdiari** [comment]
I have the same issue . i'm using rtx4060 . try diffrent drivers , try to change performance to quality , change to pcie on bios.. other games are fine .

**Comment by marcosgaming10** [comment]
Hi guys, same problem with my Nvidia 980 Ti graphic card. Any solution please? This game seems fantastic.

**Comment by romadu** [comment]
For me, the issue was caused because I had not correctly set the game exe to use NVidia card in Windows Graphics settings and it was defaulting to integrated card. Once I changed that the game displays correctly.

**Comment by marcosgaming10** [comment]
> For me, the issue was caused because I had not correctly set the game exe to use NVidia card in Windows Graphics settings and it was defaulting to integrated card. Once I changed that the game displays correctly.

Thx for very fast answer, add me on discord of you can so today i Will try to fix this problem too.. I Will show my creation.🥰
My name there Is marcosgaming10
Thanks.
