### ISSUE TITLE
Star Trek Voyager crashes on startup

### ISSUE THREAD

**Issue by BuckoA511** [teknogods/teknoparrot-issues#288]
Teknoparrot 1.0.0.1793
NVidia RTX 4090 GPU
Windows 11 Pro Build 26100
Amd Ryzen 9 5900X CPU
32GB RAM

Game does not start, simply exits, I can see this error in the command line window:-

[process exited with code 3221226505 (0xc0000409)]

Game settings were all default, ROM set fully verified.

**Comment by daveleone2** [comment]
@BuckoA511 I believe this is solved. Extract the game from MAME CHD and it fixes this problem.

**Comment by BuckoA511** [comment]
Still crashes in Teknoparrot 1.0.0.186. My ROM set 100% passes validation so it cannot be that.

**Comment by BuckoA511** [comment]
My mistake, I thought I'd try it just to humour you, I now have 5 files that fail verification but the game starts, so it seems perhaps that something is going wrong with Teknoparrot's verification?

**Comment by BuckoA511** [comment]
Nope, copying the invalid files in from my previous romset and the game 100% verifies and runs now. I must have extracted those 5 files wrong.

Can't say this makes a lot of sense to me.

**Comment by daveleone2** [comment]
Yeah, both sets of files (from the typical download and from the MAME CHD) appear to pass the validation check, so they should be binary the same.  But one set works and one set doesn't.  No clue why.

The bug is somehow related to stv.log.  If you use the original files and delete stv.log between each run, it will run.  But with the MAME CHD files you don't need to delete stv.log for it to work.  *shrug*
