### ISSUE TITLE
Fast and Furious game series input issues

### ISSUE THREAD

**Issue by legend800** [teknogods/teknoparrot-issues#63]
Remaining gamepad/input issues with various F&F games. Below are my results. All tested with 5/27 build 1.0.0.177. Don't have F&F1, Drift. I'll do my best to keep this updated.

**=Outstanding===============**

**==F&F SuperBikes 2============**
**Missing Input:**
[In Menus]	
- View (Change vehicle)

**===========================**
**=FIXED======================**

**==F&F SuperBikes 1============**
**Menu runs too fast causing repeated input (Vsync doesn’t fix)**

**Missing Input:**
[In Menus]
- View (Change vehicle- works in game which is strange)
- Tunes (Change rider)
- Enter Pin (edit: can enter directly, not on numpad apparently)

[In Game]
- Tunes (music)

**TP mappings incorrect:** 
View 1: View
View2: Shift Down
View3: Shift Up
Shift Down/Up (nothing?)

**==F&F SuperBikes 2============**
**Menu runs too fast causing repeated input (Vsync doesn’t fix)**

**Missing Input:**
[In Menus]	
- Enter Pin
- Test button/Service

[In Race]
- View (Camera)

**TP mappings incorrect:** 
View1: Shift Down
View2: Shift Up
View 3: Tunes
Shift Down/Up(nothing?)

**==F&F Supercars============**
- Shift up/down not working. 
**Menu runs too fast causing repeated input (Vsync doesn’t fix)**
Tunes mapped atop 2, 3 button (only seems to be an issue during race)

**TP mappings incorrect:** 
Shift Down/Up(nothing?)

**Missing Input:**
[In Menus]	
- Tunes (Enter Pin screen)
- Enter Pin

[In Game]
- Tunes (music)

**Comment by 00C0FFEE** [comment]
OK thank you this is very helpful report, sorry about delay.
VSYNC need a serious fix too, WIP atm.

==F&F SuperBikes 1============
Missing Input:
[In Menus] **ALL FIXED**

[In Game] **ALL FIXED**

TP mappings incorrect:
**ALL FIXED**

==F&F SuperBikes 2============
TP mappings incorrect:
**GEAR SHIFT FIXED**

==F&F ====================
TP mappings incorrect:
**GEAR SHIFT FIXED**

==F&F SuperCars =============
TP mappings incorrect:
**GEAR SHIFT FIXED**

==F&F Drift =================
TP mappings incorrect:
**GEAR SHIFT FIXED**

**Comment by legend800** [comment]
Thanks for working on this! Updated first post. Let me know if I missed anything.

**Comment by ercolino2004** [comment]
Fast n Fourious stering whell not working
Very very sensible

**Comment by legend800** [comment]
Updated defect with results from today's build. Almost completely fixed. 

Just no View/Enter Pin on SB2 and in SC, Tunes mapped atop 2, 3 button (only seems to be an issue in-game-minor)

**Comment by ercolino2004** [comment]
hello
I wanted to point out that the game Fast n Fourious has the steering wheel too sensitive practically unplayable.
regards.
all the other games in the Fast n fourious series are ok

**Comment by 00C0FFEE** [comment]
Ok, latest update should now have fixed all problems except SuperBikes2 View Button that is still WIP....
Enjoy PIN ENTRY for SB2 now!

**Comment by legend800** [comment]
Thanks for the update. I downloaded all the files from your 2 PRs and verified most everything is working now. Fantastic work!

Few notes:

SB2:
1) What is 'Other Button'? :) That should be changed to Neon.
2) I see Shift Up/Down + Shift buttons now. I'm confused....

SC:
1) NEW issue (previously untested):  Shift up/down does not work. Can't test SB2 because need View button working to access Manual transmission.

**Comment by 00C0FFEE** [comment]
**NOW FIXED in next update:**
SuperBikes2 _TEST button now working again!_
SuperBikes2 _TOGGLE MANUAL-AUTO now working!
**Shifting Gear Up** is done like this: when GAS pressed, just press SHIFT button.
**Shifting Gear Down** is done like this: when BRAKE pressed, just press SHIFT button.
SuperBikes2 _VIEW button is now working too!_
Removed old shift up/ shift down buttons from UI, and remapped some other.

**sorry but i just TESTED and SuperCars shift up/down is WORKING here**
Delete your FNFSC.xml profile in "UserProfiles" folder and re-run TPui then re-set buttons and settings.
Same goes for all FNF games, sorry.

**Comment by legend800** [comment]
Great progress! Checked every control in both games (after wiping xmls) and only find one small remaining issue. 

SB2: "View"  button still isn't work for me in Menus (supposed to change bikes on last menu screen). Fine in race.

**Comment by legend800** [comment]
Albeit it a little hacky, View is now working in menus in SB2 meaning all noted input issues have been addressed. Thanks for the diligence on this!

**Comment by nugarp** [comment]
@00C0FFEE any chance to get pin pad support in SuperCars? Just tried with a recent build and pin entry isn't registering. Thanks in advance as always. Edit: tried with an old build originally. I'm not sure it ever worked (as reported in the original post here).
